### ISSUE TITLE
Color scheme 

### ISSUE THREAD

**Issue by tpimont** [bitseater/weather#43]
Coul you please make a version with color scheme for icons ?
to be happier when there are clouds :)

![image](https://user-images.githubusercontent.com/25609323/36162209-0cef5a50-10e6-11e8-9ef2-4591b911747b.png)

**Comment by bitseater** [comment]
The application uses the icons provided by the elementary theme, so I can not change them (You can choose between realistic and symbolic icons in Preferences). You can choose another theme of icons, if you want.

In the future, it is expected that the application has its own theme, or the user can choose it, as can be seen in [ROADMAP](https://github.com/bitseater/weather/wiki).

Otherwise, you can manually change weather icons in your system.

Close the issue because a note is added in roadmap.
