### ISSUE TITLE
Use my location by default

### ISSUE THREAD

**Issue by cassidyjames** [bitseater/weather#6]
Instead of making me search for a city the first time, it'd be nice to use some sort of geolocating to use the closes detected city by default.

**Comment by bitseater** [comment]
In order to catch my location by default, it should be used the geoclue-2.0 library, like Daniel Foré's [Nimbus](https://github.com/danrabbit/nimbus) do. This library is used by gweather-3.0 to know weather conditions from near station of various providers to this location. These stations are different from OpenWeatherMap, which uses stations of individuals all over the world, following the open data philosophy.

What do you think about it? Continue using OWM or go to GWeather, whose API is maintained by the GNOME people?

**Comment by cassidyjames** [comment]
I'm not sure about the weather data itself; that might be up to you and the quality of the data. But it would be useful regardless to be able to use the nearest city/station by default. Whether that's by using GWeather, or just GeoClue and cross-referencing GPS coordinates with OWM is up to you.

**Comment by bitseater** [comment]
Fixed in Release 0.40
