### ISSUE TITLE
More frequent updates?

### ISSUE THREAD

**Issue by lilumb** [bitseater/weather#88]
The _minimum_ update frequency is currently every *2* hrs. Is it possible to make this more frequent? Ideally, every 15 minutes?

-Ian

**Comment by bitseater** [comment]
Hi @lilumb . Thanks for trying Meteo. The minimum update frecuency is set in order to prevent to block the built-in API key. If you are registered at OpenWeatherMap with your own API key and you use it in Meteo, you can manually update whenever you want. 

I am going to add more update intervals, only for users with own API key: 15 min, 30 min and 1 hour.

**Comment by lilumb** [comment]
I am now making use of my own API key, and look forward to the availability of this enhancement - thank you! 

-Ian

**Comment by bitseater** [comment]
Fixed with [6e06985](https://github.com/bitseater/weather/commit/6e0698587b2685da710cc769c404de0798319971)

**Comment by lilumb** [comment]
Thank you! Looking forward to the 0.8 release.
